source "https://rubygems.org"

ruby "3.3.0"

# Framework
gem "rails", "~> 8.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"

# Background Jobs
gem "connection_pool", "~> 2.4"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.0"

# API
gem "rack-cors"
gem "rack-attack"

# Auth
gem "devise"
gem "devise-jwt"

# Integrations
gem "google-apis-analyticsdata_v1beta"
gem "google-apis-analyticsadmin_v1beta"
gem "google-apis-drive_v3"
gem "google-ads-googleads", "~> 23.0"
gem "koala" # Meta/Facebook

# AI
gem "ruby-openai"
gem "httparty"

# Utilities
gem "pagy"
gem "dotenv-rails"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]

# Deploy
gem "kamal", require: false
gem "thruster", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-rails"
  gem "pry-byebug"
end

group :development do
  gem "annotate"
  gem "bullet"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
  gem "rubocop-performance", require: false
  gem "brakeman", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
  gem "webmock"
  gem "vcr"
  gem "simplecov", require: false
end
